"""Blueprinting canonical compiler infrastructure."""

from .axes import BindingAxis
from .bindings import (
    BindingSet,
    CalibrationBinding,
    DeploymentProfile,
    InferencePhase,
    StrategyBinding,
    TargetProfile,
    TargetRequirements,
    WorkloadBinding,
    WorkloadMode,
)
from .codec import canonical_dumps, canonical_loads, content_digest
from .errors import (
    BindingError,
    CompilerError,
    Diagnostic,
    IRVerificationError,
    MissingAnalysisError,
    MissingBindingError,
    PassContractError,
    SerializationError,
    VerificationReport,
)
from .expr import ExprOp, ScalarExpr, Symbol, ceil_div, free_symbols, maximum, minimum, substitute
from .frozen import FrozenDict, freeze, thaw
from .ids import (
    BufferId,
    CommandId,
    DeviceId,
    InstructionId,
    Lineage,
    LineageKind,
    MemoryRegionId,
    NodeId,
    QueueId,
    TokenId,
    ValueId,
)
from .session import CompilationSession

__all__ = [
    "BindingAxis",
    "BindingError",
    "BindingSet",
    "BufferId",
    "CalibrationBinding",
    "CommandId",
    "CompilationSession",
    "CompilerError",
    "DeploymentProfile",
    "DeviceId",
    "Diagnostic",
    "ExprOp",
    "FrozenDict",
    "IRVerificationError",
    "InferencePhase",
    "InstructionId",
    "Lineage",
    "LineageKind",
    "MemoryRegionId",
    "MissingAnalysisError",
    "MissingBindingError",
    "NodeId",
    "PassContractError",
    "QueueId",
    "TokenId",
    "ScalarExpr",
    "SerializationError",
    "StrategyBinding",
    "Symbol",
    "TargetProfile",
    "TargetRequirements",
    "ValueId",
    "VerificationReport",
    "WorkloadBinding",
    "WorkloadMode",
    "canonical_dumps",
    "canonical_loads",
    "ceil_div",
    "content_digest",
    "free_symbols",
    "freeze",
    "maximum",
    "minimum",
    "substitute",
    "thaw",
]
